baseurl = "https://www.fernandomc.com"
languageCode = "en-US"
title = "Fernando Medina Corey"
theme = "hpstr"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
copyright = "© Fernando Medina Corey | "
GoogleAnalytics = "UA-88768773-1"

[params]
    # favicon = "favicon.ico"
    subtitle = "Cloud Architect and Pluralsight Course Author"
    description = "I'm Fernando Medina Corey, a cloud architect, published course author for software engineering content and an avid punster."
    gtm_id = "GTM-ND5HJ7K"
    gtm_datalayer = "basic"
	[params.author]
		name = "Fernando Medina Corey"
		avatar = "/images/fernando.jpg"
		bio = "I'm Fernando Medina Corey, a cloud architect, published course author for software engineering content and an avid punster."
		github = "fernando-mc"
        twitter = "fmc_sea"
        linkedin = "fmc-sea"
        email = "fernandomc.sea@gmail.com"
	[params.image]
	  feature = "/images/colombia.png"
      credit = "Isabella Medina | ismedina.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true